# Generated by Django 5.0.6 on 2024-05-30 15:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productnaam', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voornaam', models.CharField(max_length=50)),
                ('Achternaam', models.CharField(max_length=50)),
                ('Bedrijf', models.CharField(max_length=50)),
                ('Facturatieadres', models.CharField(max_length=50)),
                ('Adres', models.CharField(max_length=50)),
                ('Telefoonnummer', models.CharField(max_length=18)),
                ('Email', models.EmailField(max_length=100)),
                ('Wachtwoord', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naam', models.CharField(max_length=100)),
                ('EAN', models.CharField(max_length=50)),
                ('Omschrijving', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Prijs', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('Image', models.ImageField(upload_to='uploads/product/')),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERPWinkel.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hoeveelheid', models.IntegerField(default=1)),
                ('Adres', models.CharField(max_length=50)),
                ('Telefoonnummer', models.CharField(max_length=18)),
                ('Datum', models.DateField(default=datetime.datetime.today)),
                ('Status', models.BooleanField(default=False)),
                ('Klant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPWinkel.klant')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPWinkel.product')),
            ],
        ),
    ]
