# Generated by Django 5.0.6 on 2024-05-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winkel', '0003_rename_is_sale_product_korting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='Korting_prijs',
        ),
    ]
