# Generated by Django 5.0.6 on 2024-05-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPWinkel', '0006_remove_product_custom_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestelling',
            name='Klant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPWinkel.klant'),
        ),
        migrations.AlterField(
            model_name='bestelling',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPWinkel.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERPWinkel.categorie'),
        ),
    ]
