# Generated by Django 5.0.6 on 2024-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPWinkel', '0007_alter_bestelling_klant_alter_bestelling_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Korting_prijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='Prijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
