# Generated by Django 5.0.6 on 2024-06-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPWinkel', '0008_alter_product_korting_prijs_alter_product_prijs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Categorie',
            options={},
        ),
    ]
