# Generated by Django 5.0.6 on 2024-06-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPWinkel', '0009_alter_categorie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'categorie'},
        ),
    ]
