# Generated by Django 5.0.6 on 2024-06-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPWinkel', '0011_alter_product_korting_prijs_alter_product_prijs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
    ]
