# Generated by Django 5.0.6 on 2024-05-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winkel', '0004_rename_sale_price_product_korting_prijs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Korting_prijs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
